#DATA_DIR如果没有配置或者值为空，则各配置项的变量$data_dir默认取本配置文件所在目录路径，否则取DATA_DIR
CORE_DICT = $data_dir/xiaoyan.dict
CRF_MODEL_DICT = $data_dir/crf_model
POS_HMM_FILE = $data_dir/pos_hmm.dict
PUNC_TIME_ALNUM_DICT = $data_dir/puncNumberTimeLetter.dict
DFA_RULE_FILE = $data_dir/ws-dfa-rule.dict
USER_DICT = $data_dir/user.dict
ENABLE_CRF = true
ENABLE_DFA_RECOGNIZER = true
ENABLE_NAME_RECOGNIZER = false
NUMBER_SPLIT_LEN = 0
